#!/usr/bin/env bash

# setup_supabase.sh – create a Supabase project and configure .env

set -e

# Prompt for Supabase project name (default: iseyaa-supabase)
read -p "Enter Supabase project name (default: iseyaa-supabase): " SUPABASE_PROJECT
SUPABASE_PROJECT=${SUPABASE_PROJECT:-iseyaa-supabase}

# Ensure Supabase CLI is installed
if ! command -v supabase &> /dev/null; then
  echo "Supabase CLI not found. Installing..."
  npm i -g supabase
fi

# Log in to Supabase (will open a browser if needed)
supabase login

# Create the project (free tier) – you may need to select an organization
supabase projects create "$SUPABASE_PROJECT" --org "$USER" --region us-east-1

# Retrieve project URL and anon key
PROJECT_URL=$(supabase projects list --json | jq -r ".[] | select(.name==\"$SUPABASE_PROJECT\") | .api_url")
ANON_KEY=$(supabase projects list --json | jq -r ".[] | select(.name==\"$SUPABASE_PROJECT\") | .anon_key")

# Write to .env (or create .env if missing)
ENV_FILE="iseyaa-ai-engine/.env"
cat > "$ENV_FILE" <<EOF
# ------------------------------------------------------------
# Supabase configuration – generated by setup_supabase.sh
# ------------------------------------------------------------
SUPABASE_URL=$PROJECT_URL
SUPABASE_ANON_KEY=$ANON_KEY
# You must also add the PostgreSQL connection string manually:
# DATABASE_URL=postgresql://<user>:<pass>@<host>:5432/<db>
EOF

echo "✅ Supabase project created and .env updated."
